version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4030:4030"
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Rt40.5np5
      - MYSQL_DATABASE=db_sgt
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local     
     
