version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4030:4030"
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
     
